image: Visual Studio 2017
clone_folder: C:\F

environment:
  ANDROID_HOME: 'C:\Android\android-sdk'
  GRADLE_USER_HOME: 'C:\G'

init:
  - ps: |
      appveyor DownloadFile "https://dl.google.com/android/repository/sdk-tools-windows-3859397.zip" -FileName "C:\android-tools.zip"
      Write-Host "Extracting SDK tools..."
      7z x "C:\android-tools.zip" -o"$env:ANDROID_HOME" | Out-Null
install:
  - ps: |
      Write-Output "" > ~\.android\repositories.cfg
      Write-Host "Installing Android packages:"
      $pkgs = '"platform-tools"', '"extras;android;m2repository"', '"extras;google;m2repository"', '"build-tools;26.0.1"', '"platforms;android-26"'
      foreach ($pkg in $pkgs) {
        Write-Host "Installing ${pkg}:"
        echo "y" | & $env:ANDROID_HOME\tools\bin\sdkmanager.bat ${pkg}
      }
build_script:
  - cmd: gradlew build --stacktrace

test: off
deploy: off
